### PR TITLE
Align tests to Psr\Container

### PR DESCRIPTION
**Pull request by szepeviktor**
@mrclay All green 🍏

### CODE REVIEW

**Comment by jasonvarga** [comment]
Beat me to it. I was just about to open a PR for this.

If you want to continue to support testing for hhvm (rather than just removing it completely), you can do this.

```
jobs:
  include:
    ...
    - php: hhvm-3.3
    - php: hhvm
  allow_failures:
    - php: hhvm-3.3
    - php: hhvm

**Comment by szepeviktor** [comment]
HHVM is a thing of the past.
But you can [open a PR](https://github.com/jasonvarga/Props/commits/master) to this PR!

**Comment by jasonvarga** [comment]
I will if @mrclay wants it. Otherwise it doesn't bother me.

**Comment by mrclay** [comment]
Thanks, y'all, this is awesome!

**Comment by mrclay** [comment]
@szepeviktor Any reason we can't test 7.2 and 7.3 as well?

**Comment by szepeviktor** [comment]
You're welcome.

I did not dare to run tests on those modern versions.
Would you like me to add those?

**Pull request merged**
