### PR TITLE
Make Props\Pimple just extend Pimple\Container

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by glensc** [comment]
:+1:

**Comment by glensc** [comment]
is Pimple support optional, i.e used only by this class? perhaps it should be moved to "suggests" not "requires" in composer?

**Comment by mrclay** [comment]
Would be better to just move the Pimple support to a separate project?

**Comment by glensc** [comment]
yes. that would make more sense. concrete solution

**Pull request merged**
