### PR TITLE
Bump psr/container to v2

### PR DESCRIPTION
**Pull request by androidacy-user**

### CODE REVIEW

**Comment by glensc** [comment]
this would mean that minumum php is 7.2, not 5.3.3:
- https://github.com/php-fig/container/blob/2.0.0/composer.json#L15

perhaps allow both versions:
```yml
        "psr/container": "^1.0|^2.0",
```

**Comment by androidacy-user** [comment]
> "Advisory: PHP 5.3 is no longer officially supported as of 30 Jun 2012. "
> https://prototype.php.net/versions/5.3.3/#:~:text=Advisory%3A%20PHP%205.3%20is%20no%20longer%20officially%20supported%20as%20of%2030%20Jun%202012.

5.3.x has been EOL for a decade now. There's little to no reason to continue to try to support it.

**Comment by androidacy-user** [comment]
Don't mean to be hasty @mrclay but bump?

**Comment by mrclay** [comment]
@glensc Are you at all interested in keeping this library viable? Maybe you could suggest concrete steps @androidacy-user could do to get this updated? It's likely I'm not going to have time to touch this until mid March.

**Comment by glensc** [comment]
I would say keep the support for old php:
- https://github.com/mrclay/Props/pull/11#issuecomment-1173776036

**Pull request merged**
